from tkinter import Frame, Label, Button
import customtkinter
from PIL import Image
import os

customtkinter.set_appearance_mode("dark")


class OtpConfigView(Frame):
    width = 900
    height = 600


    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.grid_columnconfigure(0, weight=1)

        # load and create background image
        current_path = os.path.dirname(os.path.realpath(__file__))
        self.bg_image = customtkinter.CTkImage(Image.open(current_path + "../../background/bg_gradient.jpg"),
                                               size=(self.width, self.height))
        self.bg_image_label = customtkinter.CTkLabel(self, image=self.bg_image)
        self.bg_image_label.grid(row=0, column=0)

        # create home frame
        self.otp_config_frame = customtkinter.CTkFrame(self, corner_radius=0)
        self.otp_config_frame.grid(row=0, column=0, sticky="ns")
        self.greeting_label = customtkinter.CTkLabel(self.otp_config_frame, text="Configure OTP",
                                                  font=customtkinter.CTkFont(size=20, weight="bold"))
        self.greeting_label.grid(row=0, column=0, padx=30, pady=(50, 15))

        self.description = customtkinter.CTkLabel(self.otp_config_frame, text="Scan the QR code below to configure OTP for your account")
        self.description.grid(row=2, column=0, padx=10, pady=10, sticky="ew")

        # QR Code generated by the file otpconfig.py in the controllers folder
        self.qr_code = customtkinter.CTkImage(Image.open(current_path + "../../otp.png"), size=(250, 250))
        self.qr_code_label = customtkinter.CTkLabel(self.otp_config_frame, image=self.qr_code, text="")
        self.qr_code_label.grid(row=3, column=0, padx=10, pady=10, sticky="ew")


        self.cancel_label = customtkinter.CTkLabel(self.otp_config_frame, text="Cancel registration?")
        self.cancel_btn = customtkinter.CTkButton(self.otp_config_frame, text="Cancel")
        self.cancel_label.grid(row=9, column=0, padx=10)
        self.cancel_btn.grid(row=10, column=0, padx=10, pady=5)

        
        